#!/bin/bash

DESCRIPTION_STRING="Checks status of CS lab machines"
USAGE_STRING="Usage: checkhosts [-h] [-d] [host1 host2 ...]"

HOSTS=""

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

while  [[ $# -gt 0 ]]
do

key=$1 #first command line arg

case $key in

-d|-desc|-description)
printf "%s\n" "$DESCRIPTION_STRING"
shift
exit
;;

-h|-help)
printf "%s\n" "$USAGE_STRING"
shift
exit
;;

*)
HOSTS+="$1 "
shift
;;

esac

done

PYTHON_FILE=$(find | grep "checkhosts.py")
HOST=$(python $PYTHON_FILE $HOSTS)
exitStatus=$?
if (($exitStatus != 0)); then
  printf "${RED}Error: %s${NO_COLOR}\n" "Could not connect to server"
else

  if [[ -n $HOSTS ]]; then
    echo "$HOST"
  else
    printf "Best Host: %s@cs.utexas.edu\n" "$HOST"
  fi
fi
