#!/bin/bash

DESCRIPTION_STRING="Checks status of CS lab machines"
USAGE_STRING="Usage: checkhosts [-h] [-d] [host1 host2 ...]"
PYTHON_FILE=$(find | grep "checkhosts.py")

DEBUG=0

HOSTS=""

while  [[ $# -gt 0 ]]
do

key=$1 #first command line arg

case $key in

-d|-desc|-description)
printf "%s\n" "$DESCRIPTION_STRING"
DEBUG=1
shift
break
;;

-h|-help)
printf "%s\n" "$USAGE_STRING"
DEBUG=1
shift
break
;;

*)
HOSTS+="$1 "
shift
;;

esac

done

if ((DEBUG==0)); then

HOST=$(python $PYTHON_FILE $HOSTS)

#echo "$HOST"
if [[ -n $HOSTS ]]; then
  echo "$HOST"
else
  printf "Best Host: %s@cs.utexas.edu\n" "$HOST"
fi

fi
