#!/bin/bash
DESCRIPTION_STRING="Desc: Print number of lines in a file"
USAGE_STRING="Usage: filelines <directory|file> [-h] [-d]"
PYTHON_FILE=~/CustomScripts/filelines.py

while  [[ $# -gt 0 ]]
do

key=$1

case $key in

-d|-desc|-description)
printf "%s\n" "$DESCRIPTION_STRING"
shift
exit
;;

-h|-help)
printf "%s\n" "$USAGE_STRING"
shift
exit
;;
*)
python3 "$PYTHON_FILE" $1 | sort -h
shift
;;

esac

done
