#!/bin/bash

REPOSITORY_URL=""
DESCRIPTION_STRING="Desc: Initialize a git repository using github remote url"
USAGE_STRING="Usage: gitinit [-r <repository>]"

# $# = number of args passed to script

while  [[ $# -gt 0 ]]
do

key=$1 #first command line arg

case $key in

-r|-repo|-repository)
REPOSITORY_URL=$2
shift           #moves command arg index
shift
;;

-d|-desc|-description)
REPOSITORY_URL=""
printf "%s\n" "$DESCRIPTION_STRING"
shift
break
;;

-h|-help|*)
printf "%s\n" "$USAGE_STRING"
REPOSITORY_URL=""
shift
break
;;

esac

done

if [ -n "$REPOSITORY_URL" ] #if repo_url not null
then
git init
touch .gitignore
printf "%s\n\%s\n%s\n" "._.DS_Store" ".DS_Store" ".nfs*" > .gitignore
git add -A
git commit -m "Initial commit"
git remote add origin $REPOSITORY_URL
git push -u origin master
fi
