#!/bin/bash

REPOSITORY_URL=""
DESCRIPTION_STRING="Desc: Initialize a git repository using github remote url"
USAGE_STRING="Usage: gitinit -r <repository> [-h] [-d]"

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

# $# = number of args passed to script

while  [[ $# -gt 0 ]]
do

key=$1 #first command line arg

case $key in

-r|-repo|-repository)
REPOSITORY_URL=$2
shift           #moves command arg index
shift
;;

-d|-desc|-description)
printf "%s\n" "$DESCRIPTION_STRING"
HAS_ARGS=1
shift
exit
;;

-h|-help|*)
printf "%s\n" "$USAGE_STRING"
HAS_ARGS=1
shift
exit
;;

esac

done

if [ -n "$REPOSITORY_URL" ] #if repo_url not null
then
git init
touch .gitignore
printf "%s\n\%s\n%s\n" "._.DS_Store" ".DS_Store" ".nfs*" > .gitignore
git add -A
git commit -m "Initial commit"
git remote add origin $REPOSITORY_URL
git push -u origin master
printf "${GREEN}Repository successfully initialized!${NO_COLOR}\n"

fi
