#!/bin/bash

DESCRIPTION_STRING="Presents list of directories to jump to"
USAGE_STRING="Usage: jumpto <directory> [-h] [-d]"

ROOT=~/

RED='\033[0;31m'          # Red
CYAN='\033[0;36m'         # Cyan
NO_COLOR='\033[0m'        # No Color

function findDirectory() {
  local lowercaseP=$(echo "$1" | tr '[:upper:]' '[:lower:]')
  local DIRECTORIES=$(ls -D -R $ROOT | grep -i "$lowercaseP"[[:alnum:]_]*:$)

  if [[ ${#DIRECTORIES[@]} -gt 0 ]]; then
    select opt in ${DIRECTORIES[@]}; do
      di=${opt%:}
      cd $di
      break
    done
    # for d in ${DIRECTORIES[@]}
    # do
    #   echo "cd ${d%:}"
    # done
  else
    printf "${RED}%s${NO_COLOR} %s\n" "No directory found: " "$1"
  fi
}

while  [[ $# -gt 0 ]]
do

key=$1 #first command line arg

case $key in

-d|-desc|-description)
printf "%s\n" "$DESCRIPTION_STRING"
shift
exit
;;

-h|-help)
printf "%s\n" "$USAGE_STRING"
shift
exit
;;

*)
findDirectory $1
break
;;

esac

done
