#!/bin/bash

NO_COLOR='\033[0m'        # No Color
BLACK='\033[0;30m'        # Black
RED='\033[0;31m'          # Red
GREEN='\033[0;32m'        # Green
YELLOW='\033[0;33m'       # Yellow
BLUE='\033[0;34m'         # Blue
PURPLE='\033[0;35m'       # Purple
CYAN='\033[0;36m'         # Cyan
WHITE='\033[0;37m'        # White

SCRIPT_DIRECTORY=~/CustomScripts/
DESCRIPTION_STRING="Desc: Lists all custom scripts"
USAGE_STRING="Usage: listscripts [-h] [-d]"
HAS_ARGS=0

if (($# > 0))
then
HAS_ARGS=1
fi

while  [[ $# -gt 0 ]]
do

key=$1 #first command line arg

case $key in

-d|-desc|-description)
printf "%s\n" "$DESCRIPTION_STRING"
shift
break
;;

-h|-help)
printf "%s\n" "$USAGE_STRING"
shift
break
;;

esac

done

if (($HAS_ARGS == 0))
then
 printf "${BLUE}%s\n" "------------------------------------------------------------------"
 printf "%s\n" "|                         Custom Scripts                         |"
 printf "%s${NO_COLOR}\n" "------------------------------------------------------------------"

 SCRIPTS="$(ls -I *.MD -I "*.txt" $SCRIPT_DIRECTORY)" #-1 makes new line
 for program in $SCRIPTS
 do
   printf "${GREEN}%s${NO_COLOR}\n\t%s\n\t%s\n" "·$program" "$($program -description)" "$($program -help)"
 done
fi
